FROM alpine:3.21@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45 AS build
ARG XEN_VERSION=4.19.1
WORKDIR /usr/src

# build dependencies
RUN apk update && apk add build-base git flex bison perl bash coreutils argp-standalone attr-dev curl-dev linux-headers openssl-dev python3-dev xz-dev ocaml ocamlbuild ocaml-ocamldoc dev86 iasl util-linux-dev py3-setuptools ncurses-dev spice-dev xz-dev yajl-dev zlib-dev zstd-dev perl-dev openssl-dev e2fsprogs-dev curl-dev attr-dev dtc-dev

# check out xen sources
ENV XEN_VERSION=${XEN_VERSION}
RUN git clone -b "RELEASE-$XEN_VERSION" https://github.com/xen-project/xen.git && cd xen
WORKDIR /usr/src/xen
COPY ./patches-oxenstored ./patches-oxenstored

# configure Xen build system
RUN ./configure --prefix=/usr --disable-xen --enable-tools --disable-stubdom --disable-docs

# patch build system
RUN for patch in patches-oxenstored/*.patch; do patch -p1 < $patch; done

# build oxenstore
ENV CFLAGS="-O2 -Wall -static"
ENV LDFLAGS="-static"
RUN make -C tools/include all V=1 nosharedlibs=y
RUN make -C tools/libs/call all V=1 nosharedlibs=y
RUN make -C tools/libs/ctrl all V=1 nosharedlibs=y
RUN make -C tools/libs/devicemodel all V=1 nosharedlibs=y
RUN make -C tools/libs/foreignmemory all V=1 nosharedlibs=y
RUN make -C tools/libs/gnttab all V=1 nosharedlibs=y
RUN make -C tools/libs/guest all V=1 nosharedlibs=y
RUN make -C tools/libs/evtchn all V=1 nosharedlibs=y
RUN make -C tools/libs/toolcore all V=1 nosharedlibs=y
RUN make -C tools/libs/toollog all V=1 nosharedlibs=y
RUN make -j$(nproc) -C tools/ocaml all nosharedlibs=y && strip tools/ocaml/xenstored/oxenstored
COPY ./oxenstored.service /output/usr/lib/systemd/system/oxenstored.service
RUN ln -s oxenstored.service /output/usr/lib/systemd/system/xenstored.service

## copy final oxenstored into a scratch image
FROM scratch AS final
COPY --from=build /usr/src/xen/tools/ocaml/xenstored/oxenstored /usr/sbin/oxenstored
COPY --from=build /usr/src/xen/tools/ocaml/xenstored/oxenstored.conf /etc/xen/oxenstored.conf
COPY --from=build /output/usr/lib/systemd/system /usr/lib/systemd/system
