FROM alpine:3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 AS build
ARG XEN_VERSION=4.19.1
ARG XEN_REPO=https://github.com/edera-dev/xen.git
ARG XEN_BRANCH=edera/$XEN_VERSION
WORKDIR /usr/src

# build dependencies
RUN apk update && apk add build-base git flex bison python3 gnu-efi

# check out xen sources
ENV XEN_VERSION=${XEN_VERSION}
ENV XEN_BRANCH=${XEN_BRANCH}
ENV XEN_REPO=${XEN_REPO}
RUN git clone -b "$XEN_BRANCH" $XEN_REPO

WORKDIR /usr/src/xen

# get rid of -Werror
RUN find . \( -name '*.mk' -o -name 'Make*' \) -exec sed -i -e 's/-Werror//g' {} +

# build Xen hypervisor
ENV CFLAGS=-Wno-error
RUN ./configure --prefix=/usr --enable-xen --disable-tools --disable-stubdom --disable-docs
COPY configs/xen-x86_64.config ./xen/.config
RUN make -C xen olddefconfig
RUN make -j$(nproc) xen
RUN make install-xen
RUN mkdir /xenboot; ([ -f /boot/xen ] && cp /boot/xen /xenboot/xen) || \
  ([ -f /boot/xen.gz ] && cp /boot/xen.gz /xenboot/xen.gz)

# copy final Xen hypervisor into a scratch image
FROM scratch AS final
COPY --from=build /xenboot/* /boot/
COPY --from=build /usr/lib64/efi/xen.efi /usr/share/efi/xen.efi
COPY --from=build /usr/src/xen/xen/.config /boot/xen.config
